#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 105
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 5

enum {
  anon_sym_EQ = 1,
  anon_sym_PIPE = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_COMMA = 5,
  anon_sym_COLON = 6,
  anon_sym_fn = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  sym_or_operator = 10,
  sym_and_operator = 11,
  anon_sym_EQ_EQ = 12,
  anon_sym_BANG_EQ = 13,
  anon_sym_LT = 14,
  anon_sym_GT = 15,
  anon_sym_LT_EQ = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_SLASH = 21,
  anon_sym_AT = 22,
  aux_sym_identifier_token1 = 23,
  sym_num_literal = 24,
  sym_string_literal = 25,
  sym_comment = 26,
  sym_source_file = 27,
  sym__statement = 28,
  sym_assignment = 29,
  sym__expression = 30,
  sym__base_expression = 31,
  sym_expression_chain = 32,
  sym_data_definition = 33,
  sym__data_definition_parameter_list = 34,
  sym_data_definition_parameter = 35,
  sym_function_definition = 36,
  sym__parameter_list = 37,
  sym_binary_expression = 38,
  sym_comparison_operator = 39,
  sym_add_sub_operator = 40,
  sym_mult_div_operator = 41,
  sym_parameter = 42,
  sym_column_identifier = 43,
  sym_identifier = 44,
  sym_function_call = 45,
  sym__argument_list = 46,
  sym_argument = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_expression_chain_repeat1 = 49,
  aux_sym__data_definition_parameter_list_repeat1 = 50,
  aux_sym__parameter_list_repeat1 = 51,
  aux_sym__argument_list_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_or_operator] = "or_operator",
  [sym_and_operator] = "and_operator",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_AT] = "@",
  [aux_sym_identifier_token1] = "identifier_token1",
  [sym_num_literal] = "num_literal",
  [sym_string_literal] = "string_literal",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_assignment] = "assignment",
  [sym__expression] = "_expression",
  [sym__base_expression] = "_base_expression",
  [sym_expression_chain] = "expression_chain",
  [sym_data_definition] = "data_definition",
  [sym__data_definition_parameter_list] = "_data_definition_parameter_list",
  [sym_data_definition_parameter] = "data_definition_parameter",
  [sym_function_definition] = "function_definition",
  [sym__parameter_list] = "_parameter_list",
  [sym_binary_expression] = "binary_expression",
  [sym_comparison_operator] = "comparison_operator",
  [sym_add_sub_operator] = "add_sub_operator",
  [sym_mult_div_operator] = "mult_div_operator",
  [sym_parameter] = "parameter",
  [sym_column_identifier] = "column_identifier",
  [sym_identifier] = "identifier",
  [sym_function_call] = "function_call",
  [sym__argument_list] = "_argument_list",
  [sym_argument] = "argument",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_expression_chain_repeat1] = "expression_chain_repeat1",
  [aux_sym__data_definition_parameter_list_repeat1] = "_data_definition_parameter_list_repeat1",
  [aux_sym__parameter_list_repeat1] = "_parameter_list_repeat1",
  [aux_sym__argument_list_repeat1] = "_argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_or_operator] = sym_or_operator,
  [sym_and_operator] = sym_and_operator,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [sym_num_literal] = sym_num_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_assignment] = sym_assignment,
  [sym__expression] = sym__expression,
  [sym__base_expression] = sym__base_expression,
  [sym_expression_chain] = sym_expression_chain,
  [sym_data_definition] = sym_data_definition,
  [sym__data_definition_parameter_list] = sym__data_definition_parameter_list,
  [sym_data_definition_parameter] = sym_data_definition_parameter,
  [sym_function_definition] = sym_function_definition,
  [sym__parameter_list] = sym__parameter_list,
  [sym_binary_expression] = sym_binary_expression,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_add_sub_operator] = sym_add_sub_operator,
  [sym_mult_div_operator] = sym_mult_div_operator,
  [sym_parameter] = sym_parameter,
  [sym_column_identifier] = sym_column_identifier,
  [sym_identifier] = sym_identifier,
  [sym_function_call] = sym_function_call,
  [sym__argument_list] = sym__argument_list,
  [sym_argument] = sym_argument,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_expression_chain_repeat1] = aux_sym_expression_chain_repeat1,
  [aux_sym__data_definition_parameter_list_repeat1] = aux_sym__data_definition_parameter_list_repeat1,
  [aux_sym__parameter_list_repeat1] = aux_sym__parameter_list_repeat1,
  [aux_sym__argument_list_repeat1] = aux_sym__argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_or_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_and_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_num_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__base_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_data_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__data_definition_parameter_list] = {
    .visible = false,
    .named = true,
  },
  [sym_data_definition_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter_list] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_add_sub_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_mult_div_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_column_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__argument_list] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_chain_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__data_definition_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_function = 1,
  field_left = 2,
  field_name = 3,
  field_operator = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 1},
  [1] =
    {field_left, 0},
  [2] =
    {field_function, 0},
  [3] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 3,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 7,
  [18] = 9,
  [19] = 19,
  [20] = 6,
  [21] = 8,
  [22] = 4,
  [23] = 2,
  [24] = 24,
  [25] = 5,
  [26] = 12,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 10,
  [32] = 32,
  [33] = 32,
  [34] = 14,
  [35] = 32,
  [36] = 16,
  [37] = 15,
  [38] = 11,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 43,
  [47] = 47,
  [48] = 48,
  [49] = 48,
  [50] = 47,
  [51] = 45,
  [52] = 44,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 10,
  [58] = 11,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 55,
  [64] = 54,
  [65] = 65,
  [66] = 65,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 74,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 84,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 92,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 99,
  [102] = 99,
  [103] = 103,
  [104] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(18);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(18);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == ',') ADVANCE(18);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_or_operator);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_or_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_and_operator);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_and_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'd') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_num_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 12},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_or_operator] = ACTIONS(1),
    [sym_and_operator] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [sym_num_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(96),
    [sym__statement] = STATE(30),
    [sym_assignment] = STATE(30),
    [sym__expression] = STATE(30),
    [sym__base_expression] = STATE(3),
    [sym_expression_chain] = STATE(30),
    [sym_data_definition] = STATE(3),
    [sym_function_definition] = STATE(30),
    [sym_binary_expression] = STATE(3),
    [sym_column_identifier] = STATE(3),
    [sym_identifier] = STATE(5),
    [sym_function_call] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(30),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [sym_num_literal] = ACTIONS(13),
    [sym_string_literal] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_or_operator] = ACTIONS(17),
    [sym_and_operator] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(15),
    [aux_sym_identifier_token1] = ACTIONS(17),
    [sym_num_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      sym_or_operator,
    ACTIONS(27), 1,
      sym_and_operator,
    STATE(46), 1,
      sym_comparison_operator,
    STATE(47), 1,
      sym_add_sub_operator,
    STATE(48), 1,
      sym_mult_div_operator,
    STATE(54), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(23), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(19), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [54] = 10,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_comparison_operator,
    STATE(47), 1,
      sym_add_sub_operator,
    STATE(48), 1,
      sym_mult_div_operator,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(39), 4,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      aux_sym_identifier_token1,
    ACTIONS(37), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [99] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_EQ,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(41), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [136] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_comparison_operator,
    STATE(47), 1,
      sym_add_sub_operator,
    STATE(48), 1,
      sym_mult_div_operator,
    ACTIONS(39), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(37), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [173] = 7,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_comparison_operator,
    STATE(47), 1,
      sym_add_sub_operator,
    STATE(48), 1,
      sym_mult_div_operator,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(39), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(37), 12,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [212] = 8,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_comparison_operator,
    STATE(47), 1,
      sym_add_sub_operator,
    STATE(48), 1,
      sym_mult_div_operator,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(39), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(37), 10,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [253] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_and_operator,
    STATE(46), 1,
      sym_comparison_operator,
    STATE(47), 1,
      sym_add_sub_operator,
    STATE(48), 1,
      sym_mult_div_operator,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(39), 3,
      anon_sym_fn,
      sym_or_operator,
      aux_sym_identifier_token1,
    ACTIONS(29), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [300] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(51), 16,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(55), 16,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [360] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(41), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [394] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    ACTIONS(61), 1,
      sym_or_operator,
    ACTIONS(63), 1,
      sym_and_operator,
    STATE(43), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_mult_div_operator,
    STATE(50), 1,
      sym_add_sub_operator,
    STATE(64), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(19), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(29), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [442] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(65), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [470] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(69), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [498] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 6,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(73), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [526] = 7,
    ACTIONS(3), 1,
      sym_comment,
    STATE(43), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_mult_div_operator,
    STATE(50), 1,
      sym_add_sub_operator,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 12,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [561] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_and_operator,
    STATE(43), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_mult_div_operator,
    STATE(50), 1,
      sym_add_sub_operator,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 5,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
  [602] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_fn,
    ACTIONS(82), 1,
      anon_sym_AT,
    ACTIONS(85), 1,
      aux_sym_identifier_token1,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(88), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(19), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [641] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(43), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_mult_div_operator,
    STATE(50), 1,
      sym_add_sub_operator,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 14,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [674] = 8,
    ACTIONS(3), 1,
      sym_comment,
    STATE(43), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_mult_div_operator,
    STATE(50), 1,
      sym_add_sub_operator,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(39), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 10,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [711] = 9,
    ACTIONS(3), 1,
      sym_comment,
    STATE(43), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_mult_div_operator,
    STATE(50), 1,
      sym_add_sub_operator,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(37), 6,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
  [750] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(15), 16,
      anon_sym_PIPE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [777] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(19), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [815] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 13,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [847] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(41), 14,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [877] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(19), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [915] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(24), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [953] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(27), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [991] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(19), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1029] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 14,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1053] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(25), 1,
      sym_identifier,
    STATE(79), 1,
      sym_argument,
    STATE(99), 1,
      sym__argument_list,
    ACTIONS(111), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(87), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(13), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1091] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      sym_identifier,
    STATE(79), 1,
      sym_argument,
    STATE(102), 1,
      sym__argument_list,
    ACTIONS(111), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(87), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(13), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1129] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 14,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1153] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      sym_identifier,
    STATE(79), 1,
      sym_argument,
    STATE(101), 1,
      sym__argument_list,
    ACTIONS(111), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(87), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(13), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1191] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 14,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1215] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 14,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1239] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 14,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1263] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(25), 1,
      sym_identifier,
    STATE(91), 1,
      sym_argument,
    ACTIONS(111), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(87), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(13), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1295] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(111), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(56), 2,
      sym__expression,
      sym_expression_chain,
    STATE(13), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1323] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(56), 2,
      sym__expression,
      sym_expression_chain,
    STATE(3), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1351] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(111), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(86), 2,
      sym__expression,
      sym_expression_chain,
    STATE(13), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1379] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(119), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(21), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1403] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(121), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(9), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1427] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(123), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(4), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1451] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(125), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(8), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1475] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(127), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(7), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1499] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(12), 1,
      sym_identifier,
    ACTIONS(129), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(6), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1523] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(131), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(20), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1547] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(133), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(17), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1571] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(135), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(22), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1595] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_AT,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(137), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(18), 5,
      sym__base_expression,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1619] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(139), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1637] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(145), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1658] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(141), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1679] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1696] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(55), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1728] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1743] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1758] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1773] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_parameter,
    STATE(89), 1,
      sym_identifier,
    STATE(94), 1,
      sym__parameter_list,
  [1792] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_PIPE,
    STATE(63), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(139), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1807] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    STATE(63), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(143), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1822] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_data_definition_parameter,
    STATE(98), 1,
      sym__data_definition_parameter_list,
    STATE(100), 1,
      sym_identifier,
  [1841] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_data_definition_parameter,
    STATE(100), 1,
      sym_identifier,
    STATE(104), 1,
      sym__data_definition_parameter_list,
  [1860] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 4,
      anon_sym_AT,
      aux_sym_identifier_token1,
      sym_num_literal,
      sym_string_literal,
  [1870] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 4,
      anon_sym_AT,
      aux_sym_identifier_token1,
      sym_num_literal,
      sym_string_literal,
  [1880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 4,
      anon_sym_AT,
      aux_sym_identifier_token1,
      sym_num_literal,
      sym_string_literal,
  [1890] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [1903] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym__argument_list_repeat1,
  [1916] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [1929] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym__parameter_list_repeat1,
  [1942] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(53), 1,
      sym_function_call,
    STATE(97), 1,
      sym_identifier,
  [1955] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [1968] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(53), 1,
      sym_function_call,
    STATE(92), 1,
      sym_identifier,
  [1981] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym__parameter_list_repeat1,
  [1994] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym__parameter_list_repeat1,
  [2007] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym__argument_list_repeat1,
  [2020] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(85), 1,
      sym_parameter,
    STATE(89), 1,
      sym_identifier,
  [2033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(90), 1,
      sym_data_definition_parameter,
    STATE(100), 1,
      sym_identifier,
  [2046] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym__argument_list_repeat1,
  [2059] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(93), 1,
      sym_identifier,
  [2069] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      aux_sym_identifier_token1,
    STATE(37), 1,
      sym_identifier,
  [2079] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2087] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2103] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(15), 1,
      sym_identifier,
  [2113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2121] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2129] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
  [2144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
  [2158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LBRACE,
  [2165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
  [2179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
  [2186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
  [2193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_COLON,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
  [2207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_LBRACE,
  [2221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 212,
  [SMALL_STATE(9)] = 253,
  [SMALL_STATE(10)] = 300,
  [SMALL_STATE(11)] = 330,
  [SMALL_STATE(12)] = 360,
  [SMALL_STATE(13)] = 394,
  [SMALL_STATE(14)] = 442,
  [SMALL_STATE(15)] = 470,
  [SMALL_STATE(16)] = 498,
  [SMALL_STATE(17)] = 526,
  [SMALL_STATE(18)] = 561,
  [SMALL_STATE(19)] = 602,
  [SMALL_STATE(20)] = 641,
  [SMALL_STATE(21)] = 674,
  [SMALL_STATE(22)] = 711,
  [SMALL_STATE(23)] = 750,
  [SMALL_STATE(24)] = 777,
  [SMALL_STATE(25)] = 815,
  [SMALL_STATE(26)] = 847,
  [SMALL_STATE(27)] = 877,
  [SMALL_STATE(28)] = 915,
  [SMALL_STATE(29)] = 953,
  [SMALL_STATE(30)] = 991,
  [SMALL_STATE(31)] = 1029,
  [SMALL_STATE(32)] = 1053,
  [SMALL_STATE(33)] = 1091,
  [SMALL_STATE(34)] = 1129,
  [SMALL_STATE(35)] = 1153,
  [SMALL_STATE(36)] = 1191,
  [SMALL_STATE(37)] = 1215,
  [SMALL_STATE(38)] = 1239,
  [SMALL_STATE(39)] = 1263,
  [SMALL_STATE(40)] = 1295,
  [SMALL_STATE(41)] = 1323,
  [SMALL_STATE(42)] = 1351,
  [SMALL_STATE(43)] = 1379,
  [SMALL_STATE(44)] = 1403,
  [SMALL_STATE(45)] = 1427,
  [SMALL_STATE(46)] = 1451,
  [SMALL_STATE(47)] = 1475,
  [SMALL_STATE(48)] = 1499,
  [SMALL_STATE(49)] = 1523,
  [SMALL_STATE(50)] = 1547,
  [SMALL_STATE(51)] = 1571,
  [SMALL_STATE(52)] = 1595,
  [SMALL_STATE(53)] = 1619,
  [SMALL_STATE(54)] = 1637,
  [SMALL_STATE(55)] = 1658,
  [SMALL_STATE(56)] = 1679,
  [SMALL_STATE(57)] = 1696,
  [SMALL_STATE(58)] = 1712,
  [SMALL_STATE(59)] = 1728,
  [SMALL_STATE(60)] = 1743,
  [SMALL_STATE(61)] = 1758,
  [SMALL_STATE(62)] = 1773,
  [SMALL_STATE(63)] = 1792,
  [SMALL_STATE(64)] = 1807,
  [SMALL_STATE(65)] = 1822,
  [SMALL_STATE(66)] = 1841,
  [SMALL_STATE(67)] = 1860,
  [SMALL_STATE(68)] = 1870,
  [SMALL_STATE(69)] = 1880,
  [SMALL_STATE(70)] = 1890,
  [SMALL_STATE(71)] = 1903,
  [SMALL_STATE(72)] = 1916,
  [SMALL_STATE(73)] = 1929,
  [SMALL_STATE(74)] = 1942,
  [SMALL_STATE(75)] = 1955,
  [SMALL_STATE(76)] = 1968,
  [SMALL_STATE(77)] = 1981,
  [SMALL_STATE(78)] = 1994,
  [SMALL_STATE(79)] = 2007,
  [SMALL_STATE(80)] = 2020,
  [SMALL_STATE(81)] = 2033,
  [SMALL_STATE(82)] = 2046,
  [SMALL_STATE(83)] = 2059,
  [SMALL_STATE(84)] = 2069,
  [SMALL_STATE(85)] = 2079,
  [SMALL_STATE(86)] = 2087,
  [SMALL_STATE(87)] = 2095,
  [SMALL_STATE(88)] = 2103,
  [SMALL_STATE(89)] = 2113,
  [SMALL_STATE(90)] = 2121,
  [SMALL_STATE(91)] = 2129,
  [SMALL_STATE(92)] = 2137,
  [SMALL_STATE(93)] = 2144,
  [SMALL_STATE(94)] = 2151,
  [SMALL_STATE(95)] = 2158,
  [SMALL_STATE(96)] = 2165,
  [SMALL_STATE(97)] = 2172,
  [SMALL_STATE(98)] = 2179,
  [SMALL_STATE(99)] = 2186,
  [SMALL_STATE(100)] = 2193,
  [SMALL_STATE(101)] = 2200,
  [SMALL_STATE(102)] = 2207,
  [SMALL_STATE(103)] = 2214,
  [SMALL_STATE(104)] = 2221,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__base_expression, 1),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__base_expression, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 3),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 3),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 3),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition, 3),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_definition, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_identifier, 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_identifier, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition, 4),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_definition, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(83),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(88),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_chain_repeat1, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_chain, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_chain, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2), SHIFT_REPEAT(76),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, .production_id = 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, .production_id = 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, .production_id = 4),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, .production_id = 4),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, .production_id = 4),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 8, .production_id = 4),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, .production_id = 4),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7, .production_id = 4),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2), SHIFT_REPEAT(74),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operator, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_sub_operator, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mult_div_operator, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_definition_parameter_list, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2), SHIFT_REPEAT(39),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_definition_parameter_list, 1),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_list_repeat1, 2), SHIFT_REPEAT(80),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameter_list_repeat1, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__data_definition_parameter_list_repeat1, 2),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__data_definition_parameter_list_repeat1, 2), SHIFT_REPEAT(81),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_list, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_list, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition_parameter, 3),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [228] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_hippo(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
