#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 5

enum {
  anon_sym_EQ = 1,
  anon_sym_PIPE = 2,
  anon_sym_as = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_COLON = 7,
  anon_sym_fn = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  sym_or_operator = 11,
  sym_and_operator = 12,
  anon_sym_EQ_EQ = 13,
  anon_sym_BANG_EQ = 14,
  anon_sym_LT = 15,
  anon_sym_GT = 16,
  anon_sym_LT_EQ = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_PLUS = 19,
  anon_sym_DASH = 20,
  anon_sym_STAR = 21,
  anon_sym_SLASH = 22,
  anon_sym_AT = 23,
  aux_sym_identifier_token1 = 24,
  sym_num_literal = 25,
  sym_string_literal = 26,
  sym_comment = 27,
  sym_source_file = 28,
  sym__statement = 29,
  sym_assignment = 30,
  sym__expression = 31,
  sym__base_expression = 32,
  sym_expression_chain = 33,
  sym_alias = 34,
  sym_data_definition = 35,
  sym__data_definition_parameter_list = 36,
  sym_data_definition_parameter = 37,
  sym_function_definition = 38,
  sym__parameter_list = 39,
  sym_binary_expression = 40,
  sym_comparison_operator = 41,
  sym_add_sub_operator = 42,
  sym_mult_div_operator = 43,
  sym_parameter = 44,
  sym_column_identifier = 45,
  sym_identifier = 46,
  sym_function_call = 47,
  sym__argument_list = 48,
  sym_argument = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_expression_chain_repeat1 = 51,
  aux_sym__data_definition_parameter_list_repeat1 = 52,
  aux_sym__parameter_list_repeat1 = 53,
  aux_sym__argument_list_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [anon_sym_as] = "as",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_or_operator] = "or_operator",
  [sym_and_operator] = "and_operator",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_AT] = "@",
  [aux_sym_identifier_token1] = "identifier_token1",
  [sym_num_literal] = "num_literal",
  [sym_string_literal] = "string_literal",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_assignment] = "assignment",
  [sym__expression] = "_expression",
  [sym__base_expression] = "_base_expression",
  [sym_expression_chain] = "expression_chain",
  [sym_alias] = "alias",
  [sym_data_definition] = "data_definition",
  [sym__data_definition_parameter_list] = "_data_definition_parameter_list",
  [sym_data_definition_parameter] = "data_definition_parameter",
  [sym_function_definition] = "function_definition",
  [sym__parameter_list] = "_parameter_list",
  [sym_binary_expression] = "binary_expression",
  [sym_comparison_operator] = "comparison_operator",
  [sym_add_sub_operator] = "add_sub_operator",
  [sym_mult_div_operator] = "mult_div_operator",
  [sym_parameter] = "parameter",
  [sym_column_identifier] = "column_identifier",
  [sym_identifier] = "identifier",
  [sym_function_call] = "function_call",
  [sym__argument_list] = "_argument_list",
  [sym_argument] = "argument",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_expression_chain_repeat1] = "expression_chain_repeat1",
  [aux_sym__data_definition_parameter_list_repeat1] = "_data_definition_parameter_list_repeat1",
  [aux_sym__parameter_list_repeat1] = "_parameter_list_repeat1",
  [aux_sym__argument_list_repeat1] = "_argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_or_operator] = sym_or_operator,
  [sym_and_operator] = sym_and_operator,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [sym_num_literal] = sym_num_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_assignment] = sym_assignment,
  [sym__expression] = sym__expression,
  [sym__base_expression] = sym__base_expression,
  [sym_expression_chain] = sym_expression_chain,
  [sym_alias] = sym_alias,
  [sym_data_definition] = sym_data_definition,
  [sym__data_definition_parameter_list] = sym__data_definition_parameter_list,
  [sym_data_definition_parameter] = sym_data_definition_parameter,
  [sym_function_definition] = sym_function_definition,
  [sym__parameter_list] = sym__parameter_list,
  [sym_binary_expression] = sym_binary_expression,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_add_sub_operator] = sym_add_sub_operator,
  [sym_mult_div_operator] = sym_mult_div_operator,
  [sym_parameter] = sym_parameter,
  [sym_column_identifier] = sym_column_identifier,
  [sym_identifier] = sym_identifier,
  [sym_function_call] = sym_function_call,
  [sym__argument_list] = sym__argument_list,
  [sym_argument] = sym_argument,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_expression_chain_repeat1] = aux_sym_expression_chain_repeat1,
  [aux_sym__data_definition_parameter_list_repeat1] = aux_sym__data_definition_parameter_list_repeat1,
  [aux_sym__parameter_list_repeat1] = aux_sym__parameter_list_repeat1,
  [aux_sym__argument_list_repeat1] = aux_sym__argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_or_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_and_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_num_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__base_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_data_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__data_definition_parameter_list] = {
    .visible = false,
    .named = true,
  },
  [sym_data_definition_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter_list] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_add_sub_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_mult_div_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_column_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__argument_list] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_chain_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__data_definition_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_function = 1,
  field_left = 2,
  field_name = 3,
  field_operator = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 1},
  [1] =
    {field_left, 0},
  [2] =
    {field_function, 0},
  [3] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 3,
  [17] = 17,
  [18] = 6,
  [19] = 4,
  [20] = 7,
  [21] = 9,
  [22] = 8,
  [23] = 23,
  [24] = 2,
  [25] = 25,
  [26] = 26,
  [27] = 5,
  [28] = 28,
  [29] = 29,
  [30] = 10,
  [31] = 31,
  [32] = 15,
  [33] = 14,
  [34] = 34,
  [35] = 34,
  [36] = 17,
  [37] = 13,
  [38] = 12,
  [39] = 11,
  [40] = 34,
  [41] = 41,
  [42] = 42,
  [43] = 42,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 45,
  [49] = 49,
  [50] = 50,
  [51] = 50,
  [52] = 49,
  [53] = 47,
  [54] = 46,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 11,
  [60] = 12,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 57,
  [66] = 56,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 85,
  [92] = 92,
  [93] = 93,
  [94] = 93,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 96,
  [102] = 98,
  [103] = 99,
  [104] = 104,
  [105] = 99,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == 's') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == '|') ADVANCE(15);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_or_operator);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_or_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_and_operator);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_and_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'd') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_num_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_or_operator] = ACTIONS(1),
    [sym_and_operator] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [sym_num_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(100),
    [sym__statement] = STATE(25),
    [sym_assignment] = STATE(25),
    [sym__expression] = STATE(25),
    [sym__base_expression] = STATE(3),
    [sym_expression_chain] = STATE(25),
    [sym_alias] = STATE(3),
    [sym_data_definition] = STATE(3),
    [sym_function_definition] = STATE(25),
    [sym_binary_expression] = STATE(3),
    [sym_column_identifier] = STATE(3),
    [sym_identifier] = STATE(5),
    [sym_function_call] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [sym_num_literal] = ACTIONS(13),
    [sym_string_literal] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_as] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_fn] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym_or_operator] = ACTIONS(17),
    [sym_and_operator] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(15),
    [aux_sym_identifier_token1] = ACTIONS(17),
    [sym_num_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_PIPE,
    ACTIONS(23), 1,
      anon_sym_as,
    ACTIONS(27), 1,
      sym_or_operator,
    ACTIONS(29), 1,
      sym_and_operator,
    STATE(48), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_add_sub_operator,
    STATE(50), 1,
      sym_mult_div_operator,
    STATE(56), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(25), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(19), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [57] = 8,
    ACTIONS(3), 1,
      sym_comment,
    STATE(48), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_add_sub_operator,
    STATE(50), 1,
      sym_mult_div_operator,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(39), 10,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [99] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_EQ,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(43), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [137] = 7,
    ACTIONS(3), 1,
      sym_comment,
    STATE(48), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_add_sub_operator,
    STATE(50), 1,
      sym_mult_div_operator,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(39), 12,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [177] = 10,
    ACTIONS(3), 1,
      sym_comment,
    STATE(48), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_add_sub_operator,
    STATE(50), 1,
      sym_mult_div_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(41), 5,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      aux_sym_identifier_token1,
    ACTIONS(39), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [223] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(48), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_add_sub_operator,
    STATE(50), 1,
      sym_mult_div_operator,
    ACTIONS(41), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(39), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [261] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_and_operator,
    STATE(48), 1,
      sym_comparison_operator,
    STATE(49), 1,
      sym_add_sub_operator,
    STATE(50), 1,
      sym_mult_div_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(41), 4,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      aux_sym_identifier_token1,
    ACTIONS(39), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [309] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(43), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [344] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(53), 16,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(57), 16,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [406] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(61), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(65), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [464] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(69), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [493] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_PIPE,
    ACTIONS(75), 1,
      anon_sym_as,
    ACTIONS(77), 1,
      sym_or_operator,
    ACTIONS(79), 1,
      sym_and_operator,
    STATE(45), 1,
      sym_comparison_operator,
    STATE(51), 1,
      sym_mult_div_operator,
    STATE(52), 1,
      sym_add_sub_operator,
    STATE(66), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(19), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [544] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 7,
      anon_sym_as,
      anon_sym_fn,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(81), 14,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [573] = 7,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_comparison_operator,
    STATE(51), 1,
      sym_mult_div_operator,
    STATE(52), 1,
      sym_add_sub_operator,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 13,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [609] = 8,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_comparison_operator,
    STATE(51), 1,
      sym_mult_div_operator,
    STATE(52), 1,
      sym_add_sub_operator,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 11,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [647] = 9,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_comparison_operator,
    STATE(51), 1,
      sym_mult_div_operator,
    STATE(52), 1,
      sym_add_sub_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(39), 7,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
  [687] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_and_operator,
    STATE(45), 1,
      sym_comparison_operator,
    STATE(51), 1,
      sym_mult_div_operator,
    STATE(52), 1,
      sym_add_sub_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(39), 6,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
  [729] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(45), 1,
      sym_comparison_operator,
    STATE(51), 1,
      sym_mult_div_operator,
    STATE(52), 1,
      sym_add_sub_operator,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [763] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_fn,
    ACTIONS(90), 1,
      anon_sym_AT,
    ACTIONS(93), 1,
      aux_sym_identifier_token1,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(96), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(23), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(15), 17,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [831] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(23), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [870] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(28), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [909] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_EQ,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 14,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [942] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(23), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [981] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(31), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1020] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1051] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(3), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
    STATE(23), 6,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1090] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1115] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1140] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(27), 1,
      sym_identifier,
    STATE(81), 1,
      sym_argument,
    STATE(99), 1,
      sym__argument_list,
    ACTIONS(119), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(89), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(16), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1179] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_identifier,
    STATE(81), 1,
      sym_argument,
    STATE(105), 1,
      sym__argument_list,
    ACTIONS(119), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(89), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(16), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1218] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1293] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 15,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1318] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_identifier,
    STATE(81), 1,
      sym_argument,
    STATE(103), 1,
      sym__argument_list,
    ACTIONS(119), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(89), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(16), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1357] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(27), 1,
      sym_identifier,
    STATE(86), 1,
      sym_argument,
    ACTIONS(119), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(89), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(16), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1390] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(58), 2,
      sym__expression,
      sym_expression_chain,
    STATE(3), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1419] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    ACTIONS(119), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(58), 2,
      sym__expression,
      sym_expression_chain,
    STATE(16), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1448] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    ACTIONS(119), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(90), 2,
      sym__expression,
      sym_expression_chain,
    STATE(16), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1477] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    ACTIONS(127), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(19), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1502] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(129), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(9), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1527] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(131), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(7), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1552] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(133), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(4), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1577] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(135), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(6), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1602] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(137), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(8), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1627] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    ACTIONS(139), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(22), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1652] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    ACTIONS(141), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(18), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1677] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    ACTIONS(143), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(20), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1702] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(30), 1,
      sym_identifier,
    ACTIONS(145), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(21), 6,
      sym__base_expression,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1727] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1745] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(153), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1766] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(149), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(158), 7,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(53), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1820] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1836] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1866] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [1881] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_parameter,
    STATE(92), 1,
      sym_identifier,
    STATE(104), 1,
      sym__parameter_list,
  [1900] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_PIPE,
    STATE(65), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(147), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1915] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_PIPE,
    STATE(65), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(151), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1930] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_data_definition_parameter,
    STATE(102), 1,
      sym__data_definition_parameter_list,
    STATE(108), 1,
      sym_identifier,
  [1949] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_data_definition_parameter,
    STATE(98), 1,
      sym__data_definition_parameter_list,
    STATE(108), 1,
      sym_identifier,
  [1968] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 4,
      anon_sym_AT,
      aux_sym_identifier_token1,
      sym_num_literal,
      sym_string_literal,
  [1978] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 4,
      anon_sym_AT,
      aux_sym_identifier_token1,
      sym_num_literal,
      sym_string_literal,
  [1988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 4,
      anon_sym_AT,
      aux_sym_identifier_token1,
      sym_num_literal,
      sym_string_literal,
  [1998] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [2011] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym__argument_list_repeat1,
  [2024] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [2037] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym__parameter_list_repeat1,
  [2050] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(55), 1,
      sym_function_call,
    STATE(101), 1,
      sym_identifier,
  [2063] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [2076] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(55), 1,
      sym_function_call,
    STATE(96), 1,
      sym_identifier,
  [2089] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym__parameter_list_repeat1,
  [2102] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym__parameter_list_repeat1,
  [2115] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym__argument_list_repeat1,
  [2128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(95), 1,
      sym_data_definition_parameter,
    STATE(108), 1,
      sym_identifier,
  [2141] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(88), 1,
      sym_parameter,
    STATE(92), 1,
      sym_identifier,
  [2154] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym__argument_list_repeat1,
  [2167] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(33), 1,
      sym_identifier,
  [2177] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(97), 1,
      sym_identifier,
  [2195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2203] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2219] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(14), 1,
      sym_identifier,
  [2229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2237] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      aux_sym_identifier_token1,
    STATE(36), 1,
      sym_identifier,
  [2247] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      aux_sym_identifier_token1,
    STATE(17), 1,
      sym_identifier,
  [2257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LPAREN,
  [2272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
  [2279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
  [2286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
  [2293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
  [2300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
  [2307] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
  [2314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
  [2321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
  [2328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
  [2335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
  [2342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
  [2349] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 57,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 137,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 223,
  [SMALL_STATE(9)] = 261,
  [SMALL_STATE(10)] = 309,
  [SMALL_STATE(11)] = 344,
  [SMALL_STATE(12)] = 375,
  [SMALL_STATE(13)] = 406,
  [SMALL_STATE(14)] = 435,
  [SMALL_STATE(15)] = 464,
  [SMALL_STATE(16)] = 493,
  [SMALL_STATE(17)] = 544,
  [SMALL_STATE(18)] = 573,
  [SMALL_STATE(19)] = 609,
  [SMALL_STATE(20)] = 647,
  [SMALL_STATE(21)] = 687,
  [SMALL_STATE(22)] = 729,
  [SMALL_STATE(23)] = 763,
  [SMALL_STATE(24)] = 803,
  [SMALL_STATE(25)] = 831,
  [SMALL_STATE(26)] = 870,
  [SMALL_STATE(27)] = 909,
  [SMALL_STATE(28)] = 942,
  [SMALL_STATE(29)] = 981,
  [SMALL_STATE(30)] = 1020,
  [SMALL_STATE(31)] = 1051,
  [SMALL_STATE(32)] = 1090,
  [SMALL_STATE(33)] = 1115,
  [SMALL_STATE(34)] = 1140,
  [SMALL_STATE(35)] = 1179,
  [SMALL_STATE(36)] = 1218,
  [SMALL_STATE(37)] = 1243,
  [SMALL_STATE(38)] = 1268,
  [SMALL_STATE(39)] = 1293,
  [SMALL_STATE(40)] = 1318,
  [SMALL_STATE(41)] = 1357,
  [SMALL_STATE(42)] = 1390,
  [SMALL_STATE(43)] = 1419,
  [SMALL_STATE(44)] = 1448,
  [SMALL_STATE(45)] = 1477,
  [SMALL_STATE(46)] = 1502,
  [SMALL_STATE(47)] = 1527,
  [SMALL_STATE(48)] = 1552,
  [SMALL_STATE(49)] = 1577,
  [SMALL_STATE(50)] = 1602,
  [SMALL_STATE(51)] = 1627,
  [SMALL_STATE(52)] = 1652,
  [SMALL_STATE(53)] = 1677,
  [SMALL_STATE(54)] = 1702,
  [SMALL_STATE(55)] = 1727,
  [SMALL_STATE(56)] = 1745,
  [SMALL_STATE(57)] = 1766,
  [SMALL_STATE(58)] = 1787,
  [SMALL_STATE(59)] = 1804,
  [SMALL_STATE(60)] = 1820,
  [SMALL_STATE(61)] = 1836,
  [SMALL_STATE(62)] = 1851,
  [SMALL_STATE(63)] = 1866,
  [SMALL_STATE(64)] = 1881,
  [SMALL_STATE(65)] = 1900,
  [SMALL_STATE(66)] = 1915,
  [SMALL_STATE(67)] = 1930,
  [SMALL_STATE(68)] = 1949,
  [SMALL_STATE(69)] = 1968,
  [SMALL_STATE(70)] = 1978,
  [SMALL_STATE(71)] = 1988,
  [SMALL_STATE(72)] = 1998,
  [SMALL_STATE(73)] = 2011,
  [SMALL_STATE(74)] = 2024,
  [SMALL_STATE(75)] = 2037,
  [SMALL_STATE(76)] = 2050,
  [SMALL_STATE(77)] = 2063,
  [SMALL_STATE(78)] = 2076,
  [SMALL_STATE(79)] = 2089,
  [SMALL_STATE(80)] = 2102,
  [SMALL_STATE(81)] = 2115,
  [SMALL_STATE(82)] = 2128,
  [SMALL_STATE(83)] = 2141,
  [SMALL_STATE(84)] = 2154,
  [SMALL_STATE(85)] = 2167,
  [SMALL_STATE(86)] = 2177,
  [SMALL_STATE(87)] = 2185,
  [SMALL_STATE(88)] = 2195,
  [SMALL_STATE(89)] = 2203,
  [SMALL_STATE(90)] = 2211,
  [SMALL_STATE(91)] = 2219,
  [SMALL_STATE(92)] = 2229,
  [SMALL_STATE(93)] = 2237,
  [SMALL_STATE(94)] = 2247,
  [SMALL_STATE(95)] = 2257,
  [SMALL_STATE(96)] = 2265,
  [SMALL_STATE(97)] = 2272,
  [SMALL_STATE(98)] = 2279,
  [SMALL_STATE(99)] = 2286,
  [SMALL_STATE(100)] = 2293,
  [SMALL_STATE(101)] = 2300,
  [SMALL_STATE(102)] = 2307,
  [SMALL_STATE(103)] = 2314,
  [SMALL_STATE(104)] = 2321,
  [SMALL_STATE(105)] = 2328,
  [SMALL_STATE(106)] = 2335,
  [SMALL_STATE(107)] = 2342,
  [SMALL_STATE(108)] = 2349,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__base_expression, 1),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__base_expression, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 3),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_definition, 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_identifier, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_identifier, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition, 4),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_definition, 4),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 3),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(87),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_chain_repeat1, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_chain, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_chain, 2),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2), SHIFT_REPEAT(78),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, .production_id = 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, .production_id = 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, .production_id = 4),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, .production_id = 4),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, .production_id = 4),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 8, .production_id = 4),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, .production_id = 4),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7, .production_id = 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2), SHIFT_REPEAT(76),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operator, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_sub_operator, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mult_div_operator, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_definition_parameter_list, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2), SHIFT_REPEAT(41),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_definition_parameter_list, 1),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_list_repeat1, 2), SHIFT_REPEAT(83),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameter_list_repeat1, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__data_definition_parameter_list_repeat1, 2),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__data_definition_parameter_list_repeat1, 2), SHIFT_REPEAT(82),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_list, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_list, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 1),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition_parameter, 3),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [236] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_hippo(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
