#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 120
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_EQ = 1,
  anon_sym_fn = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_PIPE = 7,
  anon_sym_as = 8,
  anon_sym_COMMA = 9,
  anon_sym_COLON = 10,
  sym_or_operator = 11,
  sym_and_operator = 12,
  anon_sym_EQ_EQ = 13,
  anon_sym_BANG_EQ = 14,
  anon_sym_LT = 15,
  anon_sym_GT = 16,
  anon_sym_LT_EQ = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_PLUS = 19,
  anon_sym_DASH = 20,
  anon_sym_STAR = 21,
  anon_sym_SLASH = 22,
  anon_sym_AT = 23,
  aux_sym_identifier_token1 = 24,
  sym_num_literal = 25,
  sym_string_literal = 26,
  sym_comment = 27,
  sym_source_file = 28,
  sym__statement = 29,
  sym_assignment = 30,
  sym__expression = 31,
  sym__base_expression = 32,
  sym_function = 33,
  sym_expression_chain = 34,
  sym_alias = 35,
  sym_data_definition = 36,
  sym__data_definition_parameter_list = 37,
  sym_data_definition_parameter = 38,
  sym__parameter_list = 39,
  sym_binary_expression = 40,
  sym_comparison_operator = 41,
  sym_add_sub_operator = 42,
  sym_mult_div_operator = 43,
  sym_parameter = 44,
  sym_column_identifier = 45,
  sym_identifier = 46,
  sym_function_call = 47,
  sym__argument_list = 48,
  sym_argument = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_expression_chain_repeat1 = 51,
  aux_sym__data_definition_parameter_list_repeat1 = 52,
  aux_sym__parameter_list_repeat1 = 53,
  aux_sym__argument_list_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [anon_sym_as] = "as",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_or_operator] = "or_operator",
  [sym_and_operator] = "and_operator",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_AT] = "@",
  [aux_sym_identifier_token1] = "identifier_token1",
  [sym_num_literal] = "num_literal",
  [sym_string_literal] = "string_literal",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_assignment] = "assignment",
  [sym__expression] = "_expression",
  [sym__base_expression] = "_base_expression",
  [sym_function] = "function",
  [sym_expression_chain] = "expression_chain",
  [sym_alias] = "alias",
  [sym_data_definition] = "data_definition",
  [sym__data_definition_parameter_list] = "_data_definition_parameter_list",
  [sym_data_definition_parameter] = "data_definition_parameter",
  [sym__parameter_list] = "_parameter_list",
  [sym_binary_expression] = "binary_expression",
  [sym_comparison_operator] = "comparison_operator",
  [sym_add_sub_operator] = "add_sub_operator",
  [sym_mult_div_operator] = "mult_div_operator",
  [sym_parameter] = "parameter",
  [sym_column_identifier] = "column_identifier",
  [sym_identifier] = "identifier",
  [sym_function_call] = "function_call",
  [sym__argument_list] = "_argument_list",
  [sym_argument] = "argument",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_expression_chain_repeat1] = "expression_chain_repeat1",
  [aux_sym__data_definition_parameter_list_repeat1] = "_data_definition_parameter_list_repeat1",
  [aux_sym__parameter_list_repeat1] = "_parameter_list_repeat1",
  [aux_sym__argument_list_repeat1] = "_argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_or_operator] = sym_or_operator,
  [sym_and_operator] = sym_and_operator,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [sym_num_literal] = sym_num_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_assignment] = sym_assignment,
  [sym__expression] = sym__expression,
  [sym__base_expression] = sym__base_expression,
  [sym_function] = sym_function,
  [sym_expression_chain] = sym_expression_chain,
  [sym_alias] = sym_alias,
  [sym_data_definition] = sym_data_definition,
  [sym__data_definition_parameter_list] = sym__data_definition_parameter_list,
  [sym_data_definition_parameter] = sym_data_definition_parameter,
  [sym__parameter_list] = sym__parameter_list,
  [sym_binary_expression] = sym_binary_expression,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_add_sub_operator] = sym_add_sub_operator,
  [sym_mult_div_operator] = sym_mult_div_operator,
  [sym_parameter] = sym_parameter,
  [sym_column_identifier] = sym_column_identifier,
  [sym_identifier] = sym_identifier,
  [sym_function_call] = sym_function_call,
  [sym__argument_list] = sym__argument_list,
  [sym_argument] = sym_argument,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_expression_chain_repeat1] = aux_sym_expression_chain_repeat1,
  [aux_sym__data_definition_parameter_list_repeat1] = aux_sym__data_definition_parameter_list_repeat1,
  [aux_sym__parameter_list_repeat1] = aux_sym__parameter_list_repeat1,
  [aux_sym__argument_list_repeat1] = aux_sym__argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_or_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_and_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_num_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__base_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_data_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__data_definition_parameter_list] = {
    .visible = false,
    .named = true,
  },
  [sym_data_definition_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter_list] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_add_sub_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_mult_div_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_column_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__argument_list] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_chain_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__data_definition_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_function = 1,
  field_left = 2,
  field_operator = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
  [field_left] = "left",
  [field_operator] = "operator",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 1},
  [1] =
    {field_left, 0},
  [2] =
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 3,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 9,
  [22] = 2,
  [23] = 8,
  [24] = 6,
  [25] = 25,
  [26] = 5,
  [27] = 4,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 30,
  [34] = 32,
  [35] = 28,
  [36] = 36,
  [37] = 30,
  [38] = 31,
  [39] = 7,
  [40] = 36,
  [41] = 10,
  [42] = 13,
  [43] = 16,
  [44] = 19,
  [45] = 15,
  [46] = 20,
  [47] = 18,
  [48] = 14,
  [49] = 11,
  [50] = 12,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 55,
  [60] = 56,
  [61] = 61,
  [62] = 58,
  [63] = 61,
  [64] = 57,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 12,
  [70] = 11,
  [71] = 68,
  [72] = 72,
  [73] = 73,
  [74] = 66,
  [75] = 73,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 76,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 80,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 94,
  [101] = 101,
  [102] = 99,
  [103] = 103,
  [104] = 104,
  [105] = 103,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 106,
  [111] = 104,
  [112] = 104,
  [113] = 113,
  [114] = 108,
  [115] = 115,
  [116] = 109,
  [117] = 117,
  [118] = 107,
  [119] = 115,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '|') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '|') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(44);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == '|') ADVANCE(20);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_or_operator);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_or_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_and_operator);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_and_operator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == 'd') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_num_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 12},
  [52] = {.lex_state = 12},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 12},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 12},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 12},
  [69] = {.lex_state = 12},
  [70] = {.lex_state = 12},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 12},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 12},
  [78] = {.lex_state = 12},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 3},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_or_operator] = ACTIONS(1),
    [sym_and_operator] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_identifier_token1] = ACTIONS(1),
    [sym_num_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(113),
    [sym__statement] = STATE(29),
    [sym_assignment] = STATE(29),
    [sym__expression] = STATE(29),
    [sym__base_expression] = STATE(3),
    [sym_function] = STATE(3),
    [sym_expression_chain] = STATE(29),
    [sym_alias] = STATE(3),
    [sym_data_definition] = STATE(3),
    [sym_binary_expression] = STATE(3),
    [sym_column_identifier] = STATE(3),
    [sym_identifier] = STATE(7),
    [sym_function_call] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [aux_sym_identifier_token1] = ACTIONS(11),
    [sym_num_literal] = ACTIONS(13),
    [sym_string_literal] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_as] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [sym_or_operator] = ACTIONS(17),
    [sym_and_operator] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(15),
    [aux_sym_identifier_token1] = ACTIONS(17),
    [sym_num_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_as,
    ACTIONS(27), 1,
      sym_or_operator,
    ACTIONS(29), 1,
      sym_and_operator,
    STATE(56), 1,
      sym_add_sub_operator,
    STATE(58), 1,
      sym_comparison_operator,
    STATE(63), 1,
      sym_mult_div_operator,
    STATE(68), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(21), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(19), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [57] = 7,
    ACTIONS(3), 1,
      sym_comment,
    STATE(56), 1,
      sym_add_sub_operator,
    STATE(58), 1,
      sym_comparison_operator,
    STATE(63), 1,
      sym_mult_div_operator,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(39), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [97] = 8,
    ACTIONS(3), 1,
      sym_comment,
    STATE(56), 1,
      sym_add_sub_operator,
    STATE(58), 1,
      sym_comparison_operator,
    STATE(63), 1,
      sym_mult_div_operator,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(39), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [139] = 10,
    ACTIONS(3), 1,
      sym_comment,
    STATE(56), 1,
      sym_add_sub_operator,
    STATE(58), 1,
      sym_comparison_operator,
    STATE(63), 1,
      sym_mult_div_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(41), 5,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      aux_sym_identifier_token1,
    ACTIONS(39), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [185] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_EQ,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(43), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [223] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_and_operator,
    STATE(56), 1,
      sym_add_sub_operator,
    STATE(58), 1,
      sym_comparison_operator,
    STATE(63), 1,
      sym_mult_div_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(41), 4,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      aux_sym_identifier_token1,
    ACTIONS(39), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [271] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(56), 1,
      sym_add_sub_operator,
    STATE(58), 1,
      sym_comparison_operator,
    STATE(63), 1,
      sym_mult_div_operator,
    ACTIONS(41), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(39), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [309] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(43), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [344] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(53), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(57), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [406] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(61), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(65), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [464] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(69), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [493] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(73), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [522] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_PIPE,
    ACTIONS(79), 1,
      anon_sym_as,
    ACTIONS(81), 1,
      sym_or_operator,
    ACTIONS(83), 1,
      sym_and_operator,
    STATE(60), 1,
      sym_add_sub_operator,
    STATE(61), 1,
      sym_mult_div_operator,
    STATE(62), 1,
      sym_comparison_operator,
    STATE(71), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(19), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [573] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(85), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(89), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [631] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 7,
      anon_sym_fn,
      anon_sym_as,
      sym_or_operator,
      sym_and_operator,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_identifier_token1,
    ACTIONS(93), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [660] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(60), 1,
      sym_add_sub_operator,
    STATE(61), 1,
      sym_mult_div_operator,
    STATE(62), 1,
      sym_comparison_operator,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [694] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 3,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(15), 17,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [722] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym_and_operator,
    STATE(60), 1,
      sym_add_sub_operator,
    STATE(61), 1,
      sym_mult_div_operator,
    STATE(62), 1,
      sym_comparison_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(39), 6,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
  [764] = 9,
    ACTIONS(3), 1,
      sym_comment,
    STATE(60), 1,
      sym_add_sub_operator,
    STATE(61), 1,
      sym_mult_div_operator,
    STATE(62), 1,
      sym_comparison_operator,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(31), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(39), 7,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
  [804] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_fn,
    ACTIONS(102), 1,
      anon_sym_AT,
    ACTIONS(105), 1,
      aux_sym_identifier_token1,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(108), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(25), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [844] = 8,
    ACTIONS(3), 1,
      sym_comment,
    STATE(60), 1,
      sym_add_sub_operator,
    STATE(61), 1,
      sym_mult_div_operator,
    STATE(62), 1,
      sym_comparison_operator,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 11,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [882] = 7,
    ACTIONS(3), 1,
      sym_comment,
    STATE(60), 1,
      sym_add_sub_operator,
    STATE(61), 1,
      sym_mult_div_operator,
    STATE(62), 1,
      sym_comparison_operator,
    ACTIONS(37), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 13,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [918] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(25), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [957] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(25), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [996] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(39), 1,
      sym_identifier,
    STATE(92), 1,
      sym_argument,
    STATE(111), 1,
      sym__argument_list,
    ACTIONS(123), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(95), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(17), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1039] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(25), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1078] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(38), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1117] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_identifier,
    STATE(92), 1,
      sym_argument,
    STATE(112), 1,
      sym__argument_list,
    ACTIONS(123), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(95), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(17), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1160] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(31), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1199] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(25), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1238] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(35), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1277] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_identifier,
    STATE(92), 1,
      sym_argument,
    STATE(104), 1,
      sym__argument_list,
    ACTIONS(123), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(95), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(17), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1320] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(25), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1359] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_EQ,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 14,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1392] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(28), 5,
      sym__statement,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
      aux_sym_source_file_repeat1,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1431] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1462] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1487] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1512] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1537] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1587] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1612] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1637] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1662] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_as,
      anon_sym_COMMA,
      sym_or_operator,
      sym_and_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1687] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(39), 1,
      sym_identifier,
    STATE(96), 1,
      sym_argument,
    ACTIONS(123), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(95), 3,
      sym_assignment,
      sym__expression,
      sym_expression_chain,
    STATE(17), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1724] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(13), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(67), 2,
      sym__expression,
      sym_expression_chain,
    STATE(3), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1757] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(41), 1,
      sym_identifier,
    ACTIONS(123), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(67), 2,
      sym__expression,
      sym_expression_chain,
    STATE(17), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1790] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(41), 1,
      sym_identifier,
    ACTIONS(123), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(97), 2,
      sym__expression,
      sym_expression_chain,
    STATE(17), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1823] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(145), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(8), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1852] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(147), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(4), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1881] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(41), 1,
      sym_identifier,
    ACTIONS(149), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(24), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1910] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(151), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(5), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1939] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(41), 1,
      sym_identifier,
    ACTIONS(153), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(23), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1968] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(41), 1,
      sym_identifier,
    ACTIONS(155), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(27), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [1997] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(41), 1,
      sym_identifier,
    ACTIONS(157), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(21), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [2026] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_fn,
    ACTIONS(119), 1,
      anon_sym_AT,
    ACTIONS(121), 1,
      aux_sym_identifier_token1,
    STATE(41), 1,
      sym_identifier,
    ACTIONS(159), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(26), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [2055] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(161), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(9), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [2084] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      aux_sym_identifier_token1,
    STATE(10), 1,
      sym_identifier,
    ACTIONS(163), 2,
      sym_num_literal,
      sym_string_literal,
    STATE(6), 7,
      sym__base_expression,
      sym_function,
      sym_alias,
      sym_data_definition,
      sym_binary_expression,
      sym_column_identifier,
      sym_function_call,
  [2113] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(165), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2131] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_PIPE,
    STATE(66), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(167), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2152] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(172), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2169] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    STATE(66), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(178), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(176), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2190] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2206] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(53), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2222] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_PIPE,
    STATE(74), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(176), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2237] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(182), 3,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2250] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    STATE(89), 1,
      sym_parameter,
    STATE(101), 1,
      sym_identifier,
    STATE(107), 1,
      sym__parameter_list,
  [2269] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_PIPE,
    STATE(74), 1,
      aux_sym_expression_chain_repeat1,
    ACTIONS(165), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2284] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_parameter,
    STATE(101), 1,
      sym_identifier,
    STATE(118), 1,
      sym__parameter_list,
  [2303] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      sym_data_definition_parameter,
    STATE(105), 1,
      sym__data_definition_parameter_list,
    STATE(117), 1,
      sym_identifier,
  [2322] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(197), 3,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2335] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_fn,
      aux_sym_identifier_token1,
    ACTIONS(201), 3,
      anon_sym_AT,
      sym_num_literal,
      sym_string_literal,
  [2348] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      sym_data_definition_parameter,
    STATE(103), 1,
      sym__data_definition_parameter_list,
    STATE(117), 1,
      sym_identifier,
  [2367] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    STATE(65), 1,
      sym_function_call,
    STATE(106), 1,
      sym_identifier,
  [2380] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [2393] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    STATE(93), 1,
      sym_data_definition_parameter,
    STATE(117), 1,
      sym_identifier,
  [2406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    STATE(98), 1,
      sym_parameter,
    STATE(101), 1,
      sym_identifier,
  [2419] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym__parameter_list_repeat1,
  [2432] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    STATE(65), 1,
      sym_function_call,
    STATE(110), 1,
      sym_identifier,
  [2445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(87), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [2458] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym__data_definition_parameter_list_repeat1,
  [2471] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym__parameter_list_repeat1,
  [2484] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym__parameter_list_repeat1,
  [2497] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym__argument_list_repeat1,
  [2510] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym__argument_list_repeat1,
  [2523] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym__argument_list_repeat1,
  [2536] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2544] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    STATE(18), 1,
      sym_identifier,
  [2554] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [2578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2586] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_identifier_token1,
    STATE(20), 1,
      sym_identifier,
  [2596] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      aux_sym_identifier_token1,
    STATE(47), 1,
      sym_identifier,
  [2606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2614] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      aux_sym_identifier_token1,
    STATE(46), 1,
      sym_identifier,
  [2624] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
  [2631] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
  [2638] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
  [2645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
  [2652] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
  [2659] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
  [2666] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
  [2673] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
  [2680] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
  [2687] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
  [2694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      ts_builtin_sym_end,
  [2701] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
  [2708] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_LPAREN,
  [2715] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LBRACE,
  [2722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_COLON,
  [2729] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
  [2736] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 57,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 139,
  [SMALL_STATE(7)] = 185,
  [SMALL_STATE(8)] = 223,
  [SMALL_STATE(9)] = 271,
  [SMALL_STATE(10)] = 309,
  [SMALL_STATE(11)] = 344,
  [SMALL_STATE(12)] = 375,
  [SMALL_STATE(13)] = 406,
  [SMALL_STATE(14)] = 435,
  [SMALL_STATE(15)] = 464,
  [SMALL_STATE(16)] = 493,
  [SMALL_STATE(17)] = 522,
  [SMALL_STATE(18)] = 573,
  [SMALL_STATE(19)] = 602,
  [SMALL_STATE(20)] = 631,
  [SMALL_STATE(21)] = 660,
  [SMALL_STATE(22)] = 694,
  [SMALL_STATE(23)] = 722,
  [SMALL_STATE(24)] = 764,
  [SMALL_STATE(25)] = 804,
  [SMALL_STATE(26)] = 844,
  [SMALL_STATE(27)] = 882,
  [SMALL_STATE(28)] = 918,
  [SMALL_STATE(29)] = 957,
  [SMALL_STATE(30)] = 996,
  [SMALL_STATE(31)] = 1039,
  [SMALL_STATE(32)] = 1078,
  [SMALL_STATE(33)] = 1117,
  [SMALL_STATE(34)] = 1160,
  [SMALL_STATE(35)] = 1199,
  [SMALL_STATE(36)] = 1238,
  [SMALL_STATE(37)] = 1277,
  [SMALL_STATE(38)] = 1320,
  [SMALL_STATE(39)] = 1359,
  [SMALL_STATE(40)] = 1392,
  [SMALL_STATE(41)] = 1431,
  [SMALL_STATE(42)] = 1462,
  [SMALL_STATE(43)] = 1487,
  [SMALL_STATE(44)] = 1512,
  [SMALL_STATE(45)] = 1537,
  [SMALL_STATE(46)] = 1562,
  [SMALL_STATE(47)] = 1587,
  [SMALL_STATE(48)] = 1612,
  [SMALL_STATE(49)] = 1637,
  [SMALL_STATE(50)] = 1662,
  [SMALL_STATE(51)] = 1687,
  [SMALL_STATE(52)] = 1724,
  [SMALL_STATE(53)] = 1757,
  [SMALL_STATE(54)] = 1790,
  [SMALL_STATE(55)] = 1823,
  [SMALL_STATE(56)] = 1852,
  [SMALL_STATE(57)] = 1881,
  [SMALL_STATE(58)] = 1910,
  [SMALL_STATE(59)] = 1939,
  [SMALL_STATE(60)] = 1968,
  [SMALL_STATE(61)] = 1997,
  [SMALL_STATE(62)] = 2026,
  [SMALL_STATE(63)] = 2055,
  [SMALL_STATE(64)] = 2084,
  [SMALL_STATE(65)] = 2113,
  [SMALL_STATE(66)] = 2131,
  [SMALL_STATE(67)] = 2152,
  [SMALL_STATE(68)] = 2169,
  [SMALL_STATE(69)] = 2190,
  [SMALL_STATE(70)] = 2206,
  [SMALL_STATE(71)] = 2222,
  [SMALL_STATE(72)] = 2237,
  [SMALL_STATE(73)] = 2250,
  [SMALL_STATE(74)] = 2269,
  [SMALL_STATE(75)] = 2284,
  [SMALL_STATE(76)] = 2303,
  [SMALL_STATE(77)] = 2322,
  [SMALL_STATE(78)] = 2335,
  [SMALL_STATE(79)] = 2348,
  [SMALL_STATE(80)] = 2367,
  [SMALL_STATE(81)] = 2380,
  [SMALL_STATE(82)] = 2393,
  [SMALL_STATE(83)] = 2406,
  [SMALL_STATE(84)] = 2419,
  [SMALL_STATE(85)] = 2432,
  [SMALL_STATE(86)] = 2445,
  [SMALL_STATE(87)] = 2458,
  [SMALL_STATE(88)] = 2471,
  [SMALL_STATE(89)] = 2484,
  [SMALL_STATE(90)] = 2497,
  [SMALL_STATE(91)] = 2510,
  [SMALL_STATE(92)] = 2523,
  [SMALL_STATE(93)] = 2536,
  [SMALL_STATE(94)] = 2544,
  [SMALL_STATE(95)] = 2554,
  [SMALL_STATE(96)] = 2562,
  [SMALL_STATE(97)] = 2570,
  [SMALL_STATE(98)] = 2578,
  [SMALL_STATE(99)] = 2586,
  [SMALL_STATE(100)] = 2596,
  [SMALL_STATE(101)] = 2606,
  [SMALL_STATE(102)] = 2614,
  [SMALL_STATE(103)] = 2624,
  [SMALL_STATE(104)] = 2631,
  [SMALL_STATE(105)] = 2638,
  [SMALL_STATE(106)] = 2645,
  [SMALL_STATE(107)] = 2652,
  [SMALL_STATE(108)] = 2659,
  [SMALL_STATE(109)] = 2666,
  [SMALL_STATE(110)] = 2673,
  [SMALL_STATE(111)] = 2680,
  [SMALL_STATE(112)] = 2687,
  [SMALL_STATE(113)] = 2694,
  [SMALL_STATE(114)] = 2701,
  [SMALL_STATE(115)] = 2708,
  [SMALL_STATE(116)] = 2715,
  [SMALL_STATE(117)] = 2722,
  [SMALL_STATE(118)] = 2729,
  [SMALL_STATE(119)] = 2736,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__base_expression, 1),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__base_expression, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 3),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 6),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 7),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 5),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition, 4),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_definition, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_identifier, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_identifier, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data_definition, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alias, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(115),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(94),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_chain_repeat1, 2),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2), SHIFT_REPEAT(85),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, .production_id = 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, .production_id = 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_chain, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_chain, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_operator, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operator, 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_chain_repeat1, 2), SHIFT_REPEAT(80),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_sub_operator, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_sub_operator, 1),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mult_div_operator, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mult_div_operator, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__data_definition_parameter_list_repeat1, 2),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__data_definition_parameter_list_repeat1, 2), SHIFT_REPEAT(82),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_list, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_definition_parameter_list, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__data_definition_parameter_list, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameter_list_repeat1, 2),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameter_list_repeat1, 2), SHIFT_REPEAT(83),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameter_list, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__argument_list_repeat1, 2), SHIFT_REPEAT(51),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument_list, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_definition_parameter, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [264] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_hippo(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
